language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - tip

before_script:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites -coverprofile=coverage.txt -covermode=atomic --race --trace

after_success:
  - bash <(curl -s https://codecov.io/bash)
